# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy TechHub Backend to Azure App Service

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código-fonte
        uses: actions/checkout@v4

      - name: Listar diretórios para depuração
        run: ls -R

      - name: Configurar cache do Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-${{ runner.os }}-

      - name: Configurar Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Executar testes com Maven
        run: |
          cd TechHub.BackEnd-main
          mvn test

      - name: Compilar o projeto com Maven
        run: |
          cd TechHub.BackEnd-main
          mvn clean package

      - name: Upload do artefato para o job de deployment
        uses: actions/upload-artifact@v4
        with:
          name: springboot-app
          path: TechHub.BackEnd-main/target/*.jar
